
---
author:
- William Findlay
title: R&eacute;sum&eacute;
date: \today
bibliography: /home/housedhorse/.bibs/uni.bib
csl: /home/housedhorse/.bibs/ieee.csl
subparagraph: yes
header-includes: |
  ``` {=latex}
  \usepackage{float}
  \usepackage{listings}
  \usepackage[hang,bf]{caption}
  \usepackage{framed}
  \usepackage[section]{placeins}

  \usepackage[dvipsnames,table]{xcolor}

  \definecolor{gray}{HTML}{606060}
  \definecolor{black}{HTML}{000000}

  \usepackage{pifont}

  \allowdisplaybreaks

  \usepackage[bottom]{footmisc}
  % fancy headers/footers
  \makeatletter
  \usepackage{fancyhdr}
  \lhead{}
  \chead{}
  \rhead{\vspace{1em}\color{gray}Last Updated: \today}
  \lfoot{}
  \cfoot{}
  \rfoot{}
  \renewcommand{\headrulewidth}{0pt}

  \usepackage{amsmath, amsfonts,amssymb, amsthm}
  \usepackage{siunitx}
  \usepackage[boxruled,lined,linesnumbered,titlenumbered]{algorithm2e}

  \usepackage{setspace}
  \usepackage{changepage}
  \usepackage[explicit]{titlesec}
  \usepackage{aliascnt}

  \floatplacement{figure}{!htbp}
  \floatplacement{table}{!htbp}
  \lstset{numbers=left,breaklines=true,frame=single,language=Python,captionpos=t,abovecaptionskip={\abovecaptionskip},
  belowcaptionskip={0.5em},aboveskip=\intextsep,showstringspaces=false,identifierstyle=\color{Blue},
  commentstyle={\color{OliveGreen}},keywordstyle={\bfseries\color{Orange}},stringstyle=\color{Purple},mathescape=true}
  \setlength{\captionmargin}{1in}

  \newgeometry{left=0.6in,top=1in,bottom=1in,right=0.6in}

  \newtheoremstyle{plain}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\itshape}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{definition}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\bfseries} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \newtheoremstyle{remark}
  {12pt}   % ABOVESPACE
  {12pt}   % BELOWSPACE
  {\normalfont}  % BODYFONT
  {0pt}       % INDENT (empty value is the same as 0pt)
  {\itshape} % HEADFONT
  {.}         % HEADPUNCT
  {5pt plus 1pt minus 1pt} % HEADSPACE
  {}          % CUSTOM-HEAD-SPEC

  \theoremstyle{plain}

  % define theorem
  \newtheorem{theorem}{Theorem}[section]
  \providecommand*{\theoremautorefname}{Theorem}

  % define lemma
  \newtheorem{lemma}{Lemma}[section]
  \providecommand*{\lemmaautorefname}{Lemma}

  % define claim
  \newtheorem{claim}{Claim}[section]
  \providecommand*{\claimautorefname}{Claim}

  % define corollary
  \newtheorem{corollary}{Corollary}[section]
  \providecommand*{\corollaryautorefname}{Corollary}

  % define proposition
  \newtheorem{proposition}{Proposition}[section]
  \providecommand*{\propositionautorefname}{Proposition}

  % define conjecture
  \newtheorem{conjecture}{Conjecture}[section]
  \providecommand*{\conjectureautorefname}{Conjecture}

  \theoremstyle{remark}

  % define observation
  \newtheorem{observation}{Observation}[section]
  \providecommand*{\observationautorefname}{Observation}

  % define remark
  \newtheorem{remark}{Remark}[section]
  \providecommand*{\remarkautorefname}{Remark}

  \theoremstyle{definition}

  % define example
  \newtheorem{example}{Example}[section]
  \providecommand*{\exampleautorefname}{Example}

  % define definition
  \newtheorem{definition}{Definition}[section]
  \providecommand*{\definitionautorefname}{Definition}

  \newcommand{\blackbox}{\hfill$\blacksquare$}
  \usepackage{tikz}
  \newcommand*\circled[1]{\tikz[baseline=(char.base)]{
              \node[shape=circle,draw,inner sep=2pt] (char) {#1};}}

  \renewcommand{\labelitemi}{$\bullet$}
  \renewcommand{\labelitemii}{\ding{226}}
  \renewcommand{\labelitemiii}{\tiny$\blacksquare$}
  \renewcommand{\labelitemiv}{\small$\triangleright$}

  \titleformat{\paragraph} % command to change
  [runin]                  % shape  (runin, etc.)
  {\bfseries}              % format (bfseries, itshape, etc.)
  {}                       % label  (thesection, thesubsection, etc.)
  {0em}                    % separation between label and body
  {#1}        % before the body
  [.]                       % after the body

  \titleformat{\subparagraph} % command to change
  [runin]                  % shape  (runin, etc.)
  {\itshape}              % format (bfseries, itshape, etc.)
  {}                       % label  (thesection, thesubsection, etc.)
  {0em}                    % separation between label and body
  {#1}        % before the body
  [.]                       % after the body

  \let\lil\lstinputlisting
  \usepackage{afterpage}
  \hypersetup{colorlinks, allcolors=., urlcolor=blue}

  \usepackage{etoolbox}% http://ctan.org/pkg/etoolbox
  \makeatletter
  \patchcmd{\lst@GLI@}% <command>
    {\def\lst@firstline{#1\relax}}% <search>
    {\def\lst@firstline{#1\relax}\def\lst@firstnumber{#1\relax}}% <replace>
    {\typeout{listings firstnumber=firstline}}% <success>
    {\typeout{listings firstnumber not set}}% <failure>
  \makeatother

  \renewcommand\lstlistlistingname{List of Listings}
  \usepackage{chngcntr}
  \counterwithin{figure}{section}
  \counterwithin{table}{section}

  \usepackage{booktabs}
  \usepackage{longtable}
  \usepackage{array}
  \usepackage{multirow}
  \usepackage{wrapfig}
  \usepackage{float}
  \usepackage{colortbl}
  \usepackage{pdflscape}
  \usepackage{tabu}
  \usepackage{threeparttable}
  \usepackage{threeparttablex}
  \usepackage[normalem]{ulem}
  \usepackage{makecell}
  \pagestyle{fancy}

  \renewcommand{\sectionautorefname}{Section}
  \renewcommand{\subsectionautorefname}{Subection}
  \renewcommand{\subsubsectionautorefname}{Subection}
  \renewcommand{\paragraphautorefname}{}
  \renewcommand{\subparagraphautorefname}{}

  \usepackage{nameref}

  \makeatletter
  \renewcommand{\theparagraph}{\bfseries \@currentlabelname}
  \renewcommand{\thesubparagraph}{\itshape \@currentlabelname}
  \makeatother

  \definecolor{purple}{HTML}{400080}

  \titleformat{\section}
  {\color{black}\Large\scshape}
  {}
  {0em}
  {#1}[{\color{gray}\hrule}]

  \titleformat{\subsection}
  {\color{black}\bfseries}
  {}
  {0em}
  {#1}

  \titleformat{\subsubsection}
  {\color{black}}
  {}
  {0em}
  {#1}[]

  \titlespacing{\section}
  {0em}{1em}{0.5em}

  \titlespacing{\subsection}
  {0em}{0.5em}{0em}

  \titlespacing{\subsubsection}
  {0em}{0.5em}{0em}

  \renewcommand{\maketitle}{\relax}

  \usepackage{enumitem}
  \setitemize{itemsep=0em}

  \newcommand{\sep}{
    {\color{black}$\bullet$}
  }
  ```
output:
  pdf_document:
    number_sections: true
    fig_crop: true
    fig_caption: true
    keep_tex: false
---

\begin{figure}
\small
\begin{minipage}[t]{0.65\textwidth}
\begin{center}
{\Huge\bfseries {\color{gray}William} Findlay}

\color{gray}

\href{https://www.github.com/housedhorse}{\color{gray}github.com/housedhorse} $\bullet$ \href{http://www.wfindlay.com}{\color{gray}wfindlay.com}\\
{\color{gray}(613) 296-1240} $\bullet$ \href{mailto:william@wfindlay.com}{\color{gray}william@wfindlay.com}
\end{center}

\color{gray}

\section{Education}
\color{black}
\textbf{Bachelor of Computer Science} \hfill \emph{Carleton University}\\
{September 2015 - April 2020} \hfill\emph {Ottawa, ON}
\color{gray}

Software Engineering Stream\\
CGPA: 11.0 (A)

\section{Work Experience}

\color{black}
\textbf{Teaching Assistant} (COMP3000 Operating Systems) \hfill \emph{Carleton University}\\
September 2018 - Present \hfill\emph {Ottawa, ON}
\color{gray}
\begin{itemize}[itemsep=0em]
\item Ran tutorial sessions for groups of 50 students.
\item Took a leadership role to ensure tutorials proceeded smoothly.
\item Held weekly office hours and workshops for students.
\item Graded assignments and tests and gave appropriate feedback.
\item Proctored exams for about 200 students.
\item Assisted professor with development and delivery of course material.
\end{itemize}

\color{black}
\textbf{Full Stack Developer} \hfill \emph{Hilltops Real Estate Group}\\
May 2018 - September 2018 \hfill\emph {(Remotely) Dallas, TX}
\color{gray}
\begin{itemize}[itemsep=0em]
\item Developed website for a startup student housing company.
\item Led a small team of developers working on full stack development of a business website.
\end{itemize}

\color{black}
\textbf{Service Department Supervisor} \hfill \emph{Metro Ontario, Inc.}\\
April 2014 - January 2018 \hfill\emph {Ottawa, ON}
\color{gray}
\begin{itemize}[itemsep=0em]
\item Managed day-to-day operations in the front end service department.
\item In charge of store payroll and accounting on a part-time basis.
\item Exhibited superior customer service skills as required.
\end{itemize}

\section{Projects \normalfont \small (See more on \href{https://www.github.com/housedhorse}{GitHub})}

\subsection{Raspberry Pi GPIO Pin Driver}
\begin{itemize}[itemsep=0em]
\item Wrote a character device driver Linux kernel module to act as a driver for GPIO pins on the Raspberry Pi.
\item Module supported read and write operations to set active pins, read pin input, and write pin output.
\item A full writeup on the module is available at \url{http://www.wfindlay.com/portfolio/written/3000report.pdf}
\end{itemize}

\subsection{Asciify (ASCII Art Generator)}
\begin{itemize}[itemsep=0em]
\item Wrote an ASCII art generator CLI in Python3.
\item Generator takes an image or GIF as input and produces ASCII art output.
\item Full support for color and black and white ASCII art.
\item Full support for ASCII animated GIFs.
\end{itemize}

\subsection{Genetic Algorithm for Text Generation}
\begin{itemize}[itemsep=0em]
\item Wrote a genetic algorithm in C++ to generate a human-readable string from random data.
\end{itemize}

\subsection{Taskmaster}
\begin{itemize}[itemsep=0em]
\item Wrote a GUI workflow management tool in Qt5 and C++.
\item Application keeps track of current tasks, upcoming tasks, and breaks and cycles through them with a timer.
\end{itemize}

\end{minipage}
\hfill
\begin{minipage}[t]{0.32\textwidth}
\color{gray}
\ %
\vspace{-1.5em}

\section{Languages}

\subsection{Programming}

\subsubsection{10,000 or more lines}

C, C++, Python, R

\subsubsection{5,000 - 10,000 lines}

Java, Javascript, Lisp

\subsubsection{1,000 - 5,000 lines}

Haskell, Prolog, Vimscript, x86-64 Intel Assembly

\subsection{Markup}

Markdown, Rmarkdown, \LaTeX, HTML, CSS

\subsection{Human}

English, French

\section{Technologies}

Qt, NodeJS, Tensorflow, ReactJS, Git, Bash

\section{Workflow}

\subsection{Operating System}
GNU/Linux (Arch Linux)

\subsection{Window Manager}
i3wm

\subsection{Terminal and Shell}
Termite, Bash

\subsection{Text Editor}
Vim

\subsection{Version Control}
Git, GitHub

\section{Technical Skills}
GNU/Linux kernel development\\
Low-level C development\\
C++ development\\
Python scripting\\
Statistical analysis in R\\
Documentation in \LaTeX{} and Rmarkdown

\section{General Skills}
Team leader\\
Dedicated\\
Goal-oriented

\section{Extracurricular}

Linux nerd and free software enthusiast\\
Computer builder\\
Study group leader for friends and peers\\
Former Grandmaster Starcraft II player

\end{minipage}
\end{figure}
